"""POST-HOC REGIME RESEARCH — NOT OUT-OF-SAMPLE VALIDATION.

Phase 3B: investigates whether causal (trailing-only) regime features can
explain *when a trend/breakout strategy should not be traded*, using the
already-consumed 2018-2024 (research) and 2025-2026 (recent, post-hoc)
periods. This module does NOT search for new strategy parameters, does NOT
grid-search thresholds, and does NOT use any machine learning. It computes
descriptive statistics and univariate separation measures only, to support
manually-authored, preregistered forward hypotheses.

Every function here is read-only with respect to Phase 3's existing frozen
forward preregistration: this module never imports, references, or writes
to src/forward/, PHASE3_FORWARD.md, breakout_forward.py, or
configs/forward_validation.yaml. `run_regime_study` calls
`assert_phase3_intact()` before and after doing anything, and aborts with a
clear error if a mismatch is detected either time.

No trade or backtest result generated by this module may be described as
out-of-sample, validated, or proven. All outputs carry the
"POST-HOC REGIME RESEARCH / NOT OUT-OF-SAMPLE VALIDATION" label.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Callable

import numpy as np
import pandas as pd
from scipy.stats import ks_2samp, mannwhitneyu

from src.backtesting.engine import BacktestConfig
from src.data.loader import dataset_hash, load_ohlcv
from src.research.holdout import split_final_holdout
from src.research.phase3_guard import Phase3IntegrityError, assert_phase3_intact
from src.research.regime_features import compute_regime_features, feature_values_at
from src.research.regime_gate_simulation import (
    adx_minimum_gate,
    run_exploratory_gate_simulation,
    volatility_compression_gate,
)
from src.strategies.breakout import Breakout
from src.strategies.sma_cross import SmaCross

MAX_HYPOTHESES = 3

# Exactly one exploratory simulation variant per hypothesis (Task 5 / Task
# 9's "no grid, no iterating" constraint, enforced structurally: this is a
# fixed tuple, not a loop over any parameter list).
EXPLORATORY_SIMULATIONS = (
    {
        "hypothesis_id": "H1_volatility_compression_gate",
        "strategy_factory": lambda: SmaCross(20, 100),
        "gate_fn": volatility_compression_gate,
        "feature_column": "realized_vol_168h",
        "output_subdir": "H1_volatility_compression_gate_sma_cross",
    },
    {
        "hypothesis_id": "H2_adx_minimum_gate",
        "strategy_factory": lambda: Breakout(168, 60),
        "gate_fn": adx_minimum_gate,
        "feature_column": "adx_14",
        "output_subdir": "H2_adx_minimum_gate_breakout_168_60",
    },
)
if len(EXPLORATORY_SIMULATIONS) > MAX_HYPOTHESES:
    raise RuntimeError("more exploratory simulations declared than MAX_HYPOTHESES allows")

LABEL = "POST-HOC REGIME RESEARCH"
LABEL_FULL = "POST-HOC REGIME RESEARCH / NOT OUT-OF-SAMPLE VALIDATION"

DEFAULT_OUTPUT_ROOT = Path("research/regime_study")
RECENT_START = "2025-01-01"
RECENT_END = "2026-09-02"

FEATURE_COLUMNS = [
    "realized_vol_24h",
    "realized_vol_168h",
    "realized_vol_720h",
    "atr_14",
    "atr_over_close_14",
    "adx_14",
    "sma50_slope",
    "sma200_slope",
    "distance_from_sma200",
    "autocorr_24h",
    "autocorr_168h",
    "efficiency_ratio_20",
    "range_compression_24_168",
    "directional_persistence_168",
    "pct_positive_bars_24h",
    "pct_positive_bars_72h",
    "pct_positive_bars_168h",
]

# The trade populations this study examines, sourced from already-generated
# artifacts (never re-backtested here). Each entry: (label, path).
TRADE_SOURCES: dict[str, dict[str, Path]] = {
    "breakout_168_60": {
        "research": Path("research/phase25/variants/variant_015_168_60/trades.csv"),
        "recent": Path("research/final_holdout/variants/breakout_168_60/trades.csv"),
    },
    "breakout_168_72": {
        "research": Path("research/phase25/variants/variant_016_168_72/trades.csv"),
        "recent": Path("research/final_holdout/variants/breakout_168_72/trades.csv"),
    },
    "sma_cross_20_100": {
        "research": Path("research/parameter_studies/sma_cross/variant_005/trades.csv"),
        "recent": Path("research/post_holdout_family_comparison/variants/sma_cross_variant_005/trades.csv"),
    },
}


def _require_phase3_intact() -> dict[str, Any]:
    try:
        return assert_phase3_intact()
    except Phase3IntegrityError as exc:
        raise Phase3IntegrityError(
            f"Refusing to run Phase 3B regime study: Phase 3 forward "
            f"preregistration is not intact. {exc}"
        ) from exc


# ---------------------------------------------------------------------------
# Task 2: feature distributions, research vs recent
# ---------------------------------------------------------------------------


def _psi(research: pd.Series, recent: pd.Series, n_bins: int = 10) -> float | None:
    """Population Stability Index between two distributions of the same
    feature, using research-period decile edges (a standard, simple PSI
    construction: bin edges are fixed from the reference/research
    distribution, then both distributions are binned into those same
    edges). Returns None if either series has too few valid values to form
    bins.
    """
    research = research.dropna()
    recent = recent.dropna()
    if len(research) < n_bins * 5 or len(recent) < n_bins * 5:
        return None

    quantiles = np.linspace(0, 1, n_bins + 1)
    edges = np.unique(research.quantile(quantiles).to_numpy())
    if len(edges) < 3:
        return None  # degenerate distribution, can't form meaningful bins

    research_counts, _ = np.histogram(research, bins=edges)
    recent_counts, _ = np.histogram(recent, bins=edges)

    research_frac = research_counts / research_counts.sum()
    recent_frac = recent_counts / recent_counts.sum()

    # Avoid log(0) / division by zero for empty bins with a small epsilon,
    # a standard PSI convention.
    eps = 1e-6
    research_frac = np.clip(research_frac, eps, None)
    recent_frac = np.clip(recent_frac, eps, None)

    return float(np.sum((recent_frac - research_frac) * np.log(recent_frac / research_frac)))


def build_feature_distributions(
    research_features: pd.DataFrame, recent_features: pd.DataFrame
) -> pd.DataFrame:
    """Compare each feature's distribution between the research and recent
    periods: mean, median, p10/p25/p75/p90, std, standardized mean
    difference, KS statistic, and PSI. No threshold is selected here --
    this is purely descriptive (Task 2).
    """
    rows = []
    for col in FEATURE_COLUMNS:
        research_vals = research_features[col].dropna()
        recent_vals = recent_features[col].dropna()
        if len(research_vals) < 30 or len(recent_vals) < 30:
            rows.append(
                {
                    "feature": col,
                    "n_research": len(research_vals),
                    "n_recent": len(recent_vals),
                    "note": "insufficient non-null observations in one or both periods",
                }
            )
            continue

        pooled_std = np.sqrt(
            ((len(research_vals) - 1) * research_vals.std(ddof=1) ** 2
             + (len(recent_vals) - 1) * recent_vals.std(ddof=1) ** 2)
            / (len(research_vals) + len(recent_vals) - 2)
        )
        standardized_diff = (
            (recent_vals.mean() - research_vals.mean()) / pooled_std if pooled_std > 0 else None
        )
        ks_stat, ks_pvalue = ks_2samp(research_vals, recent_vals)

        rows.append(
            {
                "feature": col,
                "n_research": len(research_vals),
                "n_recent": len(recent_vals),
                "research_mean": research_vals.mean(),
                "recent_mean": recent_vals.mean(),
                "research_median": research_vals.median(),
                "recent_median": recent_vals.median(),
                "research_p10": research_vals.quantile(0.10),
                "recent_p10": recent_vals.quantile(0.10),
                "research_p25": research_vals.quantile(0.25),
                "recent_p25": recent_vals.quantile(0.25),
                "research_p75": research_vals.quantile(0.75),
                "recent_p75": recent_vals.quantile(0.75),
                "research_p90": research_vals.quantile(0.90),
                "recent_p90": recent_vals.quantile(0.90),
                "research_std": research_vals.std(ddof=1),
                "recent_std": recent_vals.std(ddof=1),
                "standardized_mean_diff": standardized_diff,
                "ks_statistic": float(ks_stat),
                "ks_pvalue": float(ks_pvalue),
                "psi": _psi(research_vals, recent_vals),
                "note": "",
            }
        )
    return pd.DataFrame(rows)


# ---------------------------------------------------------------------------
# Task 3 & 4: entry-time features, winners vs losers, univariate separation
# ---------------------------------------------------------------------------


def _load_trades(path: Path) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError(
            f"Expected already-generated trade artifact not found: {path}. "
            "This module reads existing research/recent trade logs; it does "
            "not re-run any backtest."
        )
    df = pd.read_csv(path)
    df["entry_time"] = pd.to_datetime(df["entry_time"], utc=True)
    return df


def build_entry_feature_table(features: pd.DataFrame) -> pd.DataFrame:
    """For each configured trade source, attach regime-feature values as of
    each trade's entry_time (backward as-of lookup, never forward -- see
    feature_values_at), tagging period (research/recent) and outcome
    (winner/loser by net_pnl sign).
    """
    rows = []
    for strategy_name, paths in TRADE_SOURCES.items():
        for period in ("research", "recent"):
            trades = _load_trades(paths[period])
            if trades.empty:
                continue
            entry_features = feature_values_at(features, trades["entry_time"])
            for i in range(len(trades)):
                trade = trades.iloc[i]
                feat_row = entry_features.iloc[i]
                row = {
                    "strategy": strategy_name,
                    "period": period,
                    "entry_time": trade["entry_time"],
                    "net_pnl": trade["net_pnl"],
                    "return_pct": trade["return_pct"],
                    "outcome": "winner" if trade["net_pnl"] > 0 else "loser",
                }
                for col in FEATURE_COLUMNS:
                    row[col] = feat_row[col]
                rows.append(row)
    return pd.DataFrame(rows)


def _cohens_d(a: pd.Series, b: pd.Series) -> float | None:
    a, b = a.dropna(), b.dropna()
    if len(a) < 2 or len(b) < 2:
        return None
    pooled_std = np.sqrt(
        ((len(a) - 1) * a.std(ddof=1) ** 2 + (len(b) - 1) * b.std(ddof=1) ** 2)
        / (len(a) + len(b) - 2)
    )
    if pooled_std == 0:
        return None
    return float((a.mean() - b.mean()) / pooled_std)


def _univariate_auc(a: pd.Series, b: pd.Series) -> float | None:
    """AUC of using the feature alone to separate group `a` (treated as the
    positive class) from group `b`, computed directly from the
    Mann-Whitney U statistic (AUC = U / (n_a * n_b)) -- avoids adding a
    dependency on scikit-learn for a single, simple statistic.
    """
    a, b = a.dropna(), b.dropna()
    if len(a) < 2 or len(b) < 2:
        return None
    u_stat, _ = mannwhitneyu(a, b, alternative="two-sided")
    return float(u_stat / (len(a) * len(b)))


def build_winner_loser_separation(entry_features: pd.DataFrame) -> pd.DataFrame:
    """Univariate separation between winners and losers, per feature, per
    strategy, per period (Task 4). Exploratory only: reports effect sizes
    and sample counts, never selects a feature as "predictive" from a
    p-value alone, and never proposes a cutoff.
    """
    rows = []
    for (strategy, period), group in entry_features.groupby(["strategy", "period"]):
        winners = group[group["outcome"] == "winner"]
        losers = group[group["outcome"] == "loser"]
        for col in FEATURE_COLUMNS:
            w = winners[col].dropna()
            l = losers[col].dropna()
            row: dict[str, Any] = {
                "strategy": strategy,
                "period": period,
                "feature": col,
                "n_winners": len(w),
                "n_losers": len(l),
            }
            if len(w) < 5 or len(l) < 5:
                row["note"] = "fewer than 5 observations in a group; not reported"
                rows.append(row)
                continue
            row["winner_median"] = w.median()
            row["loser_median"] = l.median()
            row["median_diff"] = w.median() - l.median()
            row["cohens_d"] = _cohens_d(w, l)
            try:
                u_stat, p_value = mannwhitneyu(w, l, alternative="two-sided")
                row["mannwhitney_u"] = float(u_stat)
                row["mannwhitney_pvalue"] = float(p_value)
            except ValueError:
                row["mannwhitney_u"] = None
                row["mannwhitney_pvalue"] = None
            row["univariate_auc"] = _univariate_auc(w, l)
            row["note"] = ""
            rows.append(row)
    return pd.DataFrame(rows)


# ---------------------------------------------------------------------------
# Task 11: yearly robustness
# ---------------------------------------------------------------------------


def build_yearly_analysis(entry_features: pd.DataFrame) -> pd.DataFrame:
    """Per-year (2018-2026 YTD) trade counts, win rate, and median feature
    values at entry, per strategy. Purely descriptive -- flags whether an
    observed pattern is concentrated in one year or spread across several.
    2025/2026 rows are explicitly still post-hoc, never out-of-sample.
    """
    rows = []
    df = entry_features.copy()
    df["year"] = df["entry_time"].dt.year
    for (strategy, year), group in df.groupby(["strategy", "year"]):
        row = {
            "strategy": strategy,
            "year": int(year),
            "period_label": "research" if year < 2025 else "recent (post-hoc)",
            "n_trades": len(group),
            "win_rate": float((group["outcome"] == "winner").mean()),
            "median_net_pnl": group["net_pnl"].median(),
        }
        for col in FEATURE_COLUMNS:
            row[f"median_{col}"] = group[col].median()
        rows.append(row)
    return pd.DataFrame(rows).sort_values(["strategy", "year"])


# ---------------------------------------------------------------------------
# Orchestration
# ---------------------------------------------------------------------------


def run_regime_study(
    raw_dir: Path = Path("data/raw"),
    output_root: Path = DEFAULT_OUTPUT_ROOT,
    symbol: str = "BTCUSDT",
    timeframe: str = "1h",
) -> Path:
    baseline_fingerprint = _require_phase3_intact()

    output_root.mkdir(parents=True, exist_ok=True)

    df = load_ohlcv(symbol, timeframe, raw_dir=raw_dir)
    df = df.copy()
    df["timestamp"] = pd.to_datetime(df["timestamp"], utc=True)
    df = df.sort_values("timestamp").reset_index(drop=True)

    features = compute_regime_features(df)

    split = split_final_holdout(df, RECENT_START)
    recent_ts = pd.to_datetime(split.final_holdout["timestamp"], utc=True)
    recent_df = split.final_holdout.loc[recent_ts <= pd.Timestamp(RECENT_END, tz="UTC")]

    research_features = features[features["timestamp"] < pd.Timestamp(RECENT_START, tz="UTC")]
    recent_features = features[
        (features["timestamp"] >= pd.Timestamp(RECENT_START, tz="UTC"))
        & (features["timestamp"] <= pd.Timestamp(RECENT_END, tz="UTC"))
    ]

    feature_distributions = build_feature_distributions(research_features, recent_features)
    feature_distributions.to_csv(output_root / "feature_distributions.csv", index=False)

    entry_features = build_entry_feature_table(features)
    entry_features.to_csv(output_root / "entry_feature_analysis.csv", index=False)

    winner_loser = build_winner_loser_separation(entry_features)
    winner_loser.to_csv(output_root / "winner_loser_separation.csv", index=False)

    yearly = build_yearly_analysis(entry_features)
    yearly.to_csv(output_root / "yearly_analysis.csv", index=False)

    sim_config = BacktestConfig(initial_capital=10_000.0, trading_fee=0.001, slippage=0.0002)
    simulations_dir = output_root / "posthoc_simulations"
    simulation_reports = []
    for spec in EXPLORATORY_SIMULATIONS:
        report = run_exploratory_gate_simulation(
            spec["hypothesis_id"],
            spec["strategy_factory"],
            df,
            spec["gate_fn"],
            features[spec["feature_column"]],
            sim_config,
            timeframe,
            simulations_dir / spec["output_subdir"],
        )
        simulation_reports.append(report)

    final_fingerprint = _require_phase3_intact()
    if final_fingerprint != baseline_fingerprint:
        raise Phase3IntegrityError(
            "Phase 3 forward preregistration changed DURING this regime study run "
            "(fingerprint differs between start and end). This should be impossible "
            "since this module never writes to Phase 3's files -- investigate "
            "immediately."
        )
    with open(output_root / "PHASE3_FINGERPRINT.json", "w") as f:
        json.dump(
            {"before": baseline_fingerprint, "after": final_fingerprint},
            f,
            indent=2,
            default=str,
        )

    metadata = {
        "status": LABEL_FULL,
        "purpose": (
            "Investigates whether causal trailing-only regime features can "
            "explain when NOT to trade a trend/breakout strategy. No new "
            "strategy parameters searched. No thresholds grid-searched. No "
            "machine learning used. Produces at most 3 candidate forward "
            "hypotheses for future preregistration; does not implement or "
            "run any new forward test."
        ),
        "symbol": symbol,
        "timeframe": timeframe,
        "research_period": {
            "start": str(research_features["timestamp"].min()),
            "end": str(research_features["timestamp"].max()),
        },
        "recent_period": {"start": RECENT_START, "end": RECENT_END, "note": "POST-HOC, already consumed"},
        "dataset_hash_full": dataset_hash(df),
        "feature_columns": FEATURE_COLUMNS,
        "trade_sources": {k: {p: str(v[p]) for p in v} for k, v in TRADE_SOURCES.items()},
        "phase3_fingerprint_at_start": baseline_fingerprint,
        "phase3_fingerprint_at_end": final_fingerprint,
        "phase3_intact": True,
        "forbidden": [
            "out-of-sample", "validated", "proven",
            "grid search", "threshold search", "machine learning",
        ],
        "max_hypotheses_allowed": MAX_HYPOTHESES,
        "exploratory_simulations_run": [r["hypothesis_id"] for r in simulation_reports],
        "exploratory_simulations_summary": [
            {
                "hypothesis_id": r["hypothesis_id"],
                "baseline_total_return": r["baseline_metrics"].get("total_return"),
                "gated_total_return": r["gated_metrics"].get("total_return"),
                "gate_impact": r["gate_impact"],
            }
            for r in simulation_reports
        ],
    }
    with open(output_root / "metadata.json", "w") as f:
        json.dump(metadata, f, indent=2, default=str)

    return output_root
